#!/bin/bash

source utils.sh

scriptName="$(basename "$0")"

# NOTE: This requires GNU getopt.  On Mac OS X and FreeBSD, you have to install this separately
PARSED="$(getopt --options vd --long "verbose,debug" -n ${scriptName} -- "$@")"

if [ $? != 0 ] ; then
	log "getopt has complained about wrong arguments to stdout"
	echo "Terminating..." >&2
	exit 1
fi

eval set -- "$PARSED"

_VERBOSE=0
_DEBUG=0
while true; do
	case "$1" in
		-v | --verbose ) _VERBOSE=1; shift ;;
		-d | --debug ) _DEBUG=1; shift ;;
		-- ) shift; break ;;
		* ) break ;;
	esac
done

filename="$1"
filenameNoPath="${filename##*/}"
filenameNoExt="${filenameNoPath%.*}"

tempdir="$(mktemp -d)"
tempfile="${tempdir}/${filenameNoExt}.csv"

# Workaround for CLI calls to avoid using the running instance of LibreOffice
# Ref: https://bugs.documentfoundation.org/show_bug.cgi?id=37531
libreEnvTempdir="$(mktemp -d --suffix=.libreoffice-alt)"
libreEnvWorkaround="-env:UserInstallation=file://${libreEnvTempdir}"

log "File to convert: $filename"
log "Temp CSV directory: $tempdir"
log "Temp file: $tempfile"
libreoffice "$libreEnvWorkaround" --headless --convert-to csv --outdir "$tempdir" "$filename" 2>&1 | log
cat "$tempfile"

# Cleanup
cleanup () {
  rm -rf "$tempdir"
  rm -rf "$libreEnvTempdir"
}
trap cleanup EXIT
