#!/bin/bash




#######################################################################################################################
# Crop
# https://video.stackexchange.com/a/4571/26369
ffmpeg -i in.mp4 -filter:v "crop=out_w:out_h:x:y" out.mp4

# Preview crop
ffplay -i input -vf "crop=in_w:in_h-40"




#######################################################################################################################
# Re-encode
ffmpeg -i "originals/video.ogv" -vcodec libx264 -acodec libfaac "out.m4v"





#######################################################################################################################
# Concatenate
ffmpeg -i 1.mp4 -c copy -bsf:v h264_mp4toannexb -f mpegts intermediate1.ts
ffmpeg -i 2.m4v -c copy -bsf:v h264_mp4toannexb -f mpegts intermediate2.ts
ffmpeg -i "concat:intermediate1.ts|intermediate2.ts" -c copy -bsf:a aac_adtstoasc output.mp4





#######################################################################################################################
# Side-by-side join video
ffmpeg -i '1.mp4'  -i '2.mp4'  -filter_complex "[0:v]scale=-1:720[v0];[v0][1:v]hstack=inputs=2" 'out.m4v'





#######################################################################################################################
# Extract a video segment
# Ref: https://superuser.com/a/377407/535909

# How to cut a video USING DURATION, without re-encoding
ffmpeg -ss [start] -i 'in.mp4' -t [duration] -c copy 'out.mp4'

# How to cut a video USING TIMESTAMP, without re-encoding
ffmpeg -ss [start] -i 'in.mp4' -to [stop] -c copy 'out.mp4'

# How to cut a video, with re-encoding
ffmpeg -ss [start] -i 'in.mp4' -t [duration] -c:v libx264 -c:a aac -strict experimental -b:a 128k 'out.mp4'




#######################################################################################################################
# Cut-out (remove) part of the video
# Ref: https://askubuntu.com/a/977545/271027

# Doesn't work!
ffmpeg  -t 00:11:00 -i 'input.mp4' -map 0 -c copy 'intermediate1.mp4'
ffmpeg -ss 00:11:10 -i 'input.mp4' -map 0 -c copy 'intermediate2.mp4'
ffmpeg -i "concat:intermediate1.mp4|intermediate2.mp4" -c copy -bsf:a aac_adtstoasc output.mp4





#######################################################################################################################
# Speed up video
# Ref: https://video.stackexchange.com/a/18470/26369
ffmpeg -i input.m4v -vf "setpts=(PTS-STARTPTS)/30" -crf 18 output.m4v



######################################################################################################################
# Remove audio 
ffmpeg -i $input_file -c copy -an $output_file

