#!/bin/bash

scriptName="$(basename "$0")"
scriptDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
dateStamp=$(date --iso-8601="seconds")

source "${scriptDir}/utils.sh"

# Function to cleanup
function cleanup () {
	log "Deleting temp directory: $tempdir"
	rm -rf "$tempdir"
}

# NOTE: This requires GNU getopt.  On Mac OS X and FreeBSD, you have to install this separately
PARSED="$(getopt --options vd --long "verbose,debug" -n "$scriptName" -- "$@")"
if [ $? != 0 ] ; then
	log "getopt has complained about wrong arguments to stdout"
	echo "Terminating..." >&2
	exit 1
fi
eval set -- "$PARSED"

_VERBOSE=0
_DEBUG=0
while true; do
	case "$1" in
		-v | --verbose ) _VERBOSE=1; shift ;;
		-d | --debug ) _DEBUG=1; shift ;;
		-- ) shift; break ;;
		* ) break ;;
	esac
done
src="${@:$OPTIND:1}"; shift ;

srcNoExt="${src%.*}"
srcExt="${src##*.}"
dst="${srcNoExt}_${dateStamp}.m4v"

tempdir=$(mktemp -d)
trap cleanup EXIT
log "Temp directory: $tempdir"

log "Source file: ${src}"
log "Destination file: ${dst}"

# Rotate options
# 1=vertical flip
# 2=horizontal flip
# 3=default (vert + horiz flip)
# 4=clockwise 90 degrees
# 7=counterclockwise 90 degrees

# Quality options
# quality: Lower number is higher quality

# start-at starting point from start of video in seconds
# stop-at stopping point from start-at in seconds

# pfr (Peak Frame Rate)
# Will not increase frame rate. Prevents frame rate from exceeding this value.

command HandBrakeCLI \
	-i "$src" -o "$dst" \
	--encoder mpeg4 \
	--gain 24 \
	--ab 64 \
	--maxWidth 640 \
	--maxHeight 480 \
	--format av_mp4 \
	--quality 4 \
	--mixdown mono \
	--rotate=4 \
	--pfr 29;
	# --start-at duration:54 \
	# --stop-at duration:34 ;
	# --two-pass;
	#--preset="Normal" \

srcSize="$(du --human-readable "$src" | cut -f 1)"
destSize="$(du --human-readable "$dst" | cut -f 1)"
echo "Wrote ${src} (${srcSize}) to ${dst} (${destSize})"
