#!/bin/bash

scriptDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "${scriptDir}/utils.sh"

scriptName="$(basename "$0")"
dateStamp=$(date --iso-8601="seconds")

function verifyContinue () {
	if [[ $_INTERACTIVE -eq 1 ]]; then
		read -p "Do you want to continue? [y/n] " -n 1 -r
		echo
		if [[ ! $REPLY =~ ^[Yy]$ ]] ; then
			[[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1 # handle exits from shell or function but don't exit interactive shell
		fi
	fi
}

PARSED="$(getopt --options vdo: --long "verbose,debug,output:" -n "$scriptName" -- "$@")"
if [ $? != 0 ] ; then
	log "getopt has complained about wrong arguments to stdout"
	echo "Terminating..." >&2
	exit 1
fi
eval set -- "$PARSED"

_INTERACTIVE=1
_VERBOSE=0
_DEBUG=0
outputDir=resized
removeAudio=0
while true; do
	case "$1" in
		-v | --verbose ) _VERBOSE=1; shift ;;
		-d | --debug ) _DEBUG=1; shift ;;
		-o | --output ) outputDir="$2"; shift 2 ;;
		-- ) shift; break ;;
		* ) break ;;
	esac
done

# Positional arguments
overlayStr="${@:$OPTIND:1}"; shift;
pattern="${@:$OPTIND:1}"; shift;

if [ -z "$overlayStr" ]; then
	echo "ERROR: Missing required argument 1: image overlay string"
	exit -1
fi

if [ -z "$pattern" ]; then
	pattern='*'
	echo "ERROR: Missing required argument 2: file name pattern. Using default pattern: ${pattern}"
fi

if [ -d "$outputDir" ]; then
	echo "WARNING: Output directory \"${outputDir}\" already exists."
	verifyContinue
fi
mkdir "$outputDir" 2>/dev/null

if [ "$_VERBOSE" -eq 1 ]; then
	exec 3>&1
else
	exec 3>&1 &>/dev/null
fi

echo "Output directory = $outputDir"
echo "File name pattern = $pattern"

path=.
allFiles=$(find "$path" -maxdepth 1 -name "$pattern" -type f)
declare -a fileList=()
IFS=$'\n'
for f in ${allFiles}; do
	isVideo=$(mediainfo "$f" | grep -oP '^Video$')
	if [ -n "$isVideo" ]; then
		fileList+=($f)
	fi
done
unset IFS

numFiles=0
IFS=$'\n'
for f in "${fileList[@]}"; do
	numFiles=$((numFiles+1))
	outFile="${f##*/}"
	outFull="${outputDir}/${outFile}"
	printf "File #%d: \"%s\" (%d deg) to \"%s\"\n" "$numFiles" "$outFile" "$outFull"


	# quality: Lower number is higher quality
	# pfr (Peak Frame Rate): Will not increase frame rate. Prevents frame rate from exceeding this value.
	command ffmpeg \
		-i "$f" \
		-vf drawtext="fontfile=/usr/share/fonts/truetype/ubuntu-font-family/Ubuntu-B.ttf: \
		text=""${overlayStr}"": fontcolor=white: fontsize=24: box=1: boxcolor=black@0.5: \
		boxborderw=5: x=(w-text_w)/2: y=(h-text_h)" \
		-codec:a copy "$outFull" \
		>&3

	srcInfo="$(du --human-readable "$f" | cut -f 1 2>/dev/null)"
	dstInfo="$(du --human-readable "$outFull" | cut -f 1 2>/dev/null)"
	printf "Processed #%s: \"%s\" (%s) to \"%s\" (%s)\n" "$numFiles" "$outFile" "$srcInfo" "$outFull" "$dstInfo"
done
unset IFS
