#!/bin/bash

# References:
# https://askubuntu.com/questions/648603/how-to-create-an-animated-gif-from-mp4-video-via-command-line
# https://superuser.com/questions/268985/remove-audio-from-video-file-with-ffmpeg

fileIn="$1"
timeStart="$2" # Format: 00:01:00
timeStop="$3" # Format: 00:01:00
scaleWidth="$4"
rateDivisor=1

framesPerSec=5
presentationRate="(PTS-STARTPTS)/${rateDivisor}"

cropTopLeftPointX=0
cropTopLeftPointY=0
cropOutWidth=in_w
cropOutHeight=in_h

ffmpeg \
	-i "$fileIn" \
	-ss "$timeStart" \
	-to "$timeStop" \
	-filter:v "deshake, crop=w=${cropOutWidth}:h=${cropOutHeight}:x=${cropTopLeftPointX}:y=${cropTopLeftPointY}, scale=${scaleWidth}:-2, setsar=1, setpts=${presentationRate}, fps=fps=${framesPerSec}" \
	-f image2pipe \
	-vcodec ppm \
	-an \
	- | convert \
		-delay 5 \
		-loop 0 \
		-layers Optimize \
		- out.gif
