#!/bin/bash

source utils.sh

function wifiGetName () { iwconfig 2>&1 | grep -oP '^[a-zA-Z0-9]+(?=[ ]+IEEE.*)'; }
function wifiGetSsid () { iwconfig 2>&1 | grep -oP '(?<=ESSID:").*(?=")'; }
function wifiPlot () {
  local plot=$(mktemp --suffix=.png)
  vnstati -vs -i $(wifiGetName) -o ${plot}
  gwenview ${plot}
  rm -f ${plot}
}

function installDependencies () {
	if [[ "$(getOsVers)" == "16.04" ]]; then
		getPackages "vnstat" "python-pip"
		getPythonPackages "bs4" "lxml" "python-dateutil"
	else
		log "Unrecognized OS version. Not installed pre-requisites."
	fi
}



scriptName="$(basename "$0")"

# NOTE: This requires GNU getopt.  On Mac OS X and FreeBSD, you have to install this separately
PARSED="$(getopt --options vdi --long "verbose,debug,install" -n ${scriptName} -- "$@")"

if [ $? != 0 ] ; then
	log "getopt has complained about wrong arguments to stdout"
	echo "Terminating..." >&2
	exit 1
fi

eval set -- "$PARSED"

_VERBOSE=0
_DEBUG=0
_INSTALL=0
while true; do
	case "$1" in
		-v | --verbose ) _VERBOSE=1; shift ;;
		-d | --debug ) _DEBUG=1; shift ;;
		-i | --install ) _INSTALL=1; shift ;;
		-- ) shift; break ;;
		* ) break ;;
	esac
done

if [[ $_INSTALL -eq 1 ]]; then
	installDependencies
fi

scriptPath="$(dirname "$(readlink -f "$0")")"
wifiName="$(wifiGetName)"
vnstat -i "$wifiName" --xml d | python "$scriptPath/wifiUsageParser.py"
