#!/bin/bash

# This script functions similarly to dd, except that it gives periodic update prints to the terminal.

source utils.sh

getPackages "pv"

if [ "$#" -ne 2 ]; then
	echo "Illegal number of parameters"
	exit -1
fi

src="$1"
dest="$2"

if [ ${src: -3} == ".xz" ]
	srcImg="${src%.xz}"
	printf "Decompressing image from %s to %s" "$src" "$srcImg"
	unxz --keep "$src"
else
	srcImg="$src"
fi

srcSize="$(du --human-readable "$srcImg" | cut -f 1)"
destSize="$(sudo blockdev --getsize64 $dest)"
destSize="$(bytesToHuman ${destSize})"

echo "Preparing to write ${srcImg} (${srcSize}) to ${dest} (${destSize})"
verifyContinue

# Ref: https://unix.stackexchange.com/a/144227/154794
sudo sh -c "pv \"${srcImg}\" > \"${dest}\""
echo "Syncing cached writes"
sync
