#!/bin/bash

# This script functions similarly to dd, except that it gives periodic update prints to the terminal.
# Ref: https://www.raspberrypi.org/documentation/installation/installing-images/linux.md


# Verify that the required package has been installed
# Ref: http://stackoverflow.com/a/10439058
function getPackage () {
	package="dcfldd"
	if [ $(dpkg-query -W -f='${Status}' "$package" 2>/dev/null | grep -c "ok installed") -eq 0 ]; then
		echo "Package ${package} not installed. Installing it now."
		sudo apt-get --force-yes --yes install "${package}"
	fi
}

# Ref: http://unix.stackexchange.com/a/259254
bytesToHuman() {
	b=${1:-0}; d=''; s=0; S=(Bytes {K,M,G,T,E,P,Y,Z}iB)
	while ((b > 1024)); do
		d="$(printf ".%02d" $((b % 1024 * 100 / 1024)))"
		b=$((b / 1024))
		let s++
	done
	echo "$b$d ${S[$s]}"
}

getPackage

if [ "$#" -ne 2 ]; then
	echo "Illegal number of parameters"
	exit -1
fi

src="$1"
dest="$2"
blockSize="4M"

srcSize="$(du --human-readable "$src" | cut -f 1)"

destSize="$(sudo blockdev --getsize64 $dest)"
destSize="$(bytesToHuman ${destSize})"

echo "Preparing to write ${src} (${srcSize}) to ${dest} (${destSize}) in ${blockSize} chunks"

read -p "Are you sure? " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]] ; then
	[[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1 # handle exits from shell or function but don't exit interactive shell
fi

sudo dcfldd statusinterval=64 bs="${blockSize}" if="$src" of="$dest"
echo "Syncing cached writes"
sync
