#!/bin/bash

# This script functions similarly to dd, except that it gives periodic update prints to the terminal.

source utils.sh

if [ -x "$(command -v pv 2> /dev/null)" ] || [ -x "$(command -v unxz 2> /dev/null)" ]; then
	sudo apt-get install --yes pv xz-utils
fi

if [ "$#" -ne 2 ]; then
	printf "Illegal number of parameters\n"
	exit -1
fi

src="$1"
dest="$2"

if [ ${src: -3} == ".xz" ]; then
	srcImg="${src%.xz}"
	printf "Decompressing image from \"%s\" to \"%s\"\n" "$src" "$srcImg"
	unxz --keep "$src"
else
	srcImg="$src"
fi

srcSize="$(du --human-readable "$srcImg" | cut -f 1)"
destSize="$(sudo blockdev --getsize64 $dest)"
destSize="$(bytesToHuman ${destSize})"

printf "Preparing to write \"%s\" (%s) to \"%s\" (%s)\n" "$srcImg" "$srcSize" "$dest" "$destSize"
verifyContinue

# Ref: https://unix.stackexchange.com/a/144227/154794
sudo sh -c "pv \"${srcImg}\" > \"${dest}\""
printf "Syncing cached writes\n"
sync
