#!/bin/bash

# This script functions similarly to dd, except that it gives periodic update prints to the terminal.

source utils.sh

getPackages "pv"

if [ "$#" -ne 2 ]; then
	echo "Illegal number of parameters"
	exit -1
fi

src="$1"
dest="$2"
srcSize="$(du --human-readable "$src" | cut -f 1)"
destSize="$(sudo blockdev --getsize64 $dest)"
destSize="$(bytesToHuman ${destSize})"

echo "Preparing to write ${src} (${srcSize}) to ${dest} (${destSize})"
verifyContinue

# if [src == '.xz']
# 	unxz --keep "$src"
# 	src=
# fi

# Ref: https://unix.stackexchange.com/a/144227/154794
sudo sh -c "pv \"${src}\" > \"${dest}\""
echo "Syncing cached writes"
sync
