#!/usr/bin/env python

import sys
from bs4 import BeautifulSoup
from textwrap import wrap

try:
    fp = open(sys.argv[1], 'r')
except IndexError:
    fp = sys.stdin

for line in wrap(BeautifulSoup(fp, 'lxml').prettify(), replace_whitespace=False):
	print(line)
